server:
  port: 10000

spring:
 application.name: CropDeals-Gateway
 
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka       
      
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
